---
- name: "Handle ZFS dataset {{ zdataset.name }}"
  become: true
  community.general.zfs:
    extra_zfs_properties: "{{ zdataset.zfs_properties | d(omit) }}"
    name: "{{ zdataset.name }}"
    state: "{{ zdataset.state | d('present') }}"
    origin: "{{ zdataset.origin | d(omit) }}"
  ignore_errors: "{{ ansible_check_mode }}"
