---
- tags: pool
  block:
    - name: "Gather pool facts for pool \"{{ zpool[0] }}\""
      become: true
      community.general.zpool_facts:
        name: "{{ zpool[0] }}"
      register: gather_zpool_facts_out
      # task will fail if zpool does not exist, this is the expected behaviour and no error.
      ignore_errors: true

    - ansible.builtin.debug:
        var: item
      loop: "{{ ansible_zfs_pools }}"
      ignore_errors: true

    - name: "Create zpool \"{{ zpool[0] }}\""
      ansible.builtin.shell: "zpool create {{ zpool[0] }} {{ zpool[1].mode | d('') }} {{ zpool[1].disks | join(' ') }}"
