---
- tags: pool
  block:
    - name: "Gather pool facts for pool \"{{ zpool.name }}\""
      become: true
      community.general.zpool_facts:
        name: "{{ zpool.name }}"
      register: gather_zpool_facts_out
      # task will fail if zpool does not exist, this is the expected behaviour and no error.
      ignore_errors: true

- name: "Import tasks depending on pool operation"
  ansible.builtin.include_tasks: "pool/{{ zpool.operation }}.yml"
